CREATE TABLE `mst_menu` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `parent_id` INT DEFAULT NULL,
    `title` VARCHAR(255) NOT NULL,
    `url` VARCHAR(255) DEFAULT NULL,
    `icon` VARCHAR(255) DEFAULT NULL,
    `type` ENUM('menu', 'submenu', 'title') NOT NULL,
    `level` INT NOT NULL,
    FOREIGN KEY (`parent_id`) REFERENCES `mst_menu` (`id`) ON DELETE CASCADE
);

INSERT INTO
    `mst_menu` (
        `id`,
        `parent_id`,
        `title`,
        `url`,
        `icon`,
        `type`,
        `level`
    )
VALUES (
        1,
        NULL,
        'Beranda',
        NULL,
        'fa-home',
        'menu',
        1
    ),
    (
        2,
        1,
        'Ubah Profile Pengguna',
        'index.html',
        NULL,
        'submenu',
        2
    ),
    (
        3,
        NULL,
        'Dashboard',
        NULL,
        'fa-bar-chart-o',
        'menu',
        1
    ),
    (
        4,
        NULL,
        'Opac',
        NULL,
        'fa-desktop',
        'menu',
        1
    ),
    (
        5,
        NULL,
        'ETD',
        NULL,
        'fa-book',
        'menu',
        1
    ),
    (
        6,
        5,
        'Bibliografi',
        '#',
        NULL,
        'title',
        2
    ),
    (
        7,
        6,
        'Etd List',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        8,
        6,
        'Send Email Approved',
        '#',
        NULL,
        'submenu',
        3
    ), 
    (
        9,
        NULL,
        'Membership',
        NULL,
        'fa-user',
        'menu',
        1
    ),
    (
        10,
        9,
        'Keanggotaan',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        11,
        10,
        'Lihat Daftar Anggota',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        12,
        10,
        'Tambah Anggota',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        13,
        10,
        'Tipe Keanggotaan',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        14,
        9,
        'Peralatan',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        15,
        14,
        'Kartu Anggota',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        16,
        14,
        'Export Data',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        17,
        14,
        'Import Data',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        18,
        NULL,
        'Master File',
        NULL,
        'fa-file',
        'menu',
        1
    ),
    (
        19,
        18,
        'Daftar Terkendali',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        20,
        19,
        'GMD',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        21,
        19,
        'Penerbit',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        22,
        19,
        'Pengarang',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        23,
        19,
        'Dosen Pembimbing',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        24,
        19,
        'Dosen Penguji',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        25,
        19,
        'Lokasi',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        26,
        18,
        'Daftar Referensi',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        27,
        26,
        'Tempat',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        28,
        26,
        'Status Eksemplar',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        29,
        26,
        'Tipe Koleksi',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        30,
        26,
        'Bahasa Dokumen',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        31,
        26,
        'Kala Tertib',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        32,
        18,
        'Peralatan',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        33,
        32,
        'Data Pengarang Mubazir',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        34,
        32,
        'Data Subyek Mubazir',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        35,
        32,
        'Data Tempat Terbit Mubazir',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        36,
        NULL,
        'System',
        NULL,
        'fa-sitemap',
        'menu',
        1
    ),
    (
        37,
        36,
        'Sistem',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        38,
        37,
        'Pengaturan Sistem',
        'http://localhost:8081/sistem/pengaturan-sistem',
        NULL,
        'submenu',
        3
    ),
    (
        39,
        37,
        'Konten',
        'http://localhost:8081/sistem/konten',
        NULL,
        'submenu',
        3
    ),
    (
        40,
        37,
        'Pintasan',
        'http://localhost:8081/sistem/pintasan',
        NULL,
        'submenu',
        3
    ),
    (
        41,
        37,
        'Indeks Biblio',
        'http://localhost:8081/sistem/indeks-bliblio',
        NULL,
        'submenu',
        3
    ),
    (
        42,
        37,
        'Modul',
        'http://localhost:8081/sistem/modul',
        NULL,
        'submenu',
        3
    ),
    (
        43,
        37,
        'Pustaka Pengguna Sistem',
        'http://localhost:8081/sistem/pustakawan',
        NULL,
        'submenu',
        3
    ),
    (
        44,
        37,
        'Kelompok Pengguna',
        'http://localhost:8081/sistem/user-groups',
        NULL,
        'submenu',
        3
    ),
    (
        45,
        37,
        'Format Scan Generator',
        'http://localhost:8081/sistem/barcode',
        NULL,
        'submenu',
        3
    ),
    (
        46,
        37,
        'Catatan Sistem',
        'http://localhost:8081/sistem/logs',
        NULL,
        'submenu',
        3
    ),
    (
        47,
        37,
        'Salinan Pangkalan Data',
        'http://localhost:8081/sistem/backups',
        NULL,
        'submenu',
        3
    ),
    (
        48,
        NULL,
        'Reporting',
        NULL,
        'fa-table',
        'menu',
        1
    ),
    (
        49,
        48,
        'Pelaporan',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        50,
        49,
        'Statistik Koleksi',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        51,
        49,
        'Laporan Anggota',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        52,
        48,
        'Laporan Lain',
        NULL,
        NULL,
        'title',
        2
    ),
    (
        53,
        52,
        'Rekapitulasi',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        54,
        52,
        'Daftar Judul',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        55,
        52,
        'Daftar Anggota',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        56,
        52,
        'Contributor List',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        57,
        52,
        'Aktifitas Staf',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        58,
        52,
        'Statistik Pengunjung',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        59,
        52,
        'Statistik Pengunjung (per Hari)',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        60,
        52,
        'Messages.daftar Pengunjungs',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        61,
        52,
        'Visualize Diagram',
        '#',
        NULL,
        'submenu',
        3
    ),
    (
        62,
        NULL,
        'Logout',
        NULL,
        'fa-power-off',
        'menu',
        1
    );